### ISSUE TITLE
导出excel后的发票号码因科学计数法丢失

### ISSUE THREAD

**Issue by edwardpro888** [unAlpha/Invoice-Terminator#1]
发票号码24952000000010910141，导出excel时会显示为2.4952E+19。如果能解决这个问题就太完美了！！

**Comment by unAlpha** [comment]
拖大列宽就可以显示了
2024年2月12日 +0800 15:46 edwardpro888 ***@***.***>，写道：

**Comment by Rookiestm** [comment]
大佬，拖大列宽就显示24952000000010900000，想请教下应当如何修改这个功能

**Comment by unAlpha** [comment]
发票可以发给我参考吗，我测试一下

**Comment by Rookiestm** [comment]
不好意思，没有及时看到，我看网站上您已经删除请求了。请问还需要吗？
另外我不太会使用git，如果您还需要，我发邮件给您。
--

发件人: ***@***.***&gt;
发送时间: 2024年5月4日(周六) 晚上8:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [unAlpha/Invoice-Terminator] 导出excel后的发票号码因科学计数法丢失 (Issue #1)




 
发票可以发给我参考吗，我测试一下

**Comment by unAlpha** [comment]
已经在3.4的版本中解决，请重新下载3.4及以后的版本。
