### ISSUE TITLE
导出后的发票号的后四位被统一四舍五入归0了

### ISSUE THREAD

**Issue by bohailaoyao** [unAlpha/Invoice-Terminator#2]
识别出来的发票号：
****2000000022587691
****2000000005665277
****7000000114207457
导出到excel表格的发票号：
****2000000022590000
****2000000005660000
****7000000114210000
建议改成文本格式导出。另外能更改自动重命名的参数么

**Comment by Rookiestm** [comment]
请问这个问题解决了嘛？
我现在正遇到这个问题，想请教一下解决办法？

**Comment by unAlpha** [comment]
已经在3.4的版本中解决。
